{
    "status_code": 15,
    "lang": "python3",
    "run_success": false,
    "runtime_error": "Line 38: TypeError: 0 is not valid value for the expected return type integer[]",
    "full_runtime_error": "TypeError: 0 is not valid value for the expected return type integer[]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    raise TypeError(str(ret) + \" is not valid value for the expected return type integer[]\");\nLine 38 in _driver (Solution.py)\n    _driver()\nLine 45 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: 'int' object is not iterable\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 59 in _serialize (./python3/__serializer__.py)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    out = ser._serialize(ret, 'integer[]')\nLine 36 in _driver (Solution.py)",
    "status_runtime": "N/A",
    "memory": 16740000,
    "question_id": "1",
    "elapsed_time": 52,
    "compare_result": "000000000000000000000000000000000000000000000000000000000000000",
    "code_output": "",
    "std_output": "",
    "last_testcase": "[2,7,11,15]\n9",
    "expected_output": "[0,1]",
    "task_finish_time": 1723220288903,
    "task_name": "judger.judgetask.Judge",
    "finished": true,
    "total_correct": 0,
    "total_testcases": 63,
    "runtime_percentile": null,
    "status_memory": "N/A",
    "memory_percentile": null,
    "pretty_lang": "Python3",
    "submission_id": "1350140323",
    "status_msg": "Runtime Error",
    "state": "SUCCESS"
}